# 1. read through csv produced by binary ML model (animals or no animals)
# 2. for each item in the csv, make a copy of the image file if prediction certainty is above a given threshold
# 3. move the image copy to a separate folder

import csv
import os
import shutil

# define variables
confidence_threshold = 0.85
my_image_directory = "2020-07-16-Camera5"
my_predict_run = "predict-run-10/"

# set paths
my_prediction_path = "D:/non-dropbox-files/research/looking-at-animals-prediction-runs/" + my_predict_run
destination_directory = my_prediction_path + "predicted-animal-images" + str(confidence_threshold) + "_confidence"

# this is the csv file generated by the machine learning model
myCSV = my_prediction_path + "my-predictions/output-" + my_image_directory + ".csv"

print(myCSV)
print(destination_directory)

# create a folder for the animal images
if not os.path.exists(destination_directory):
    os.makedirs(destination_directory)


with open(myCSV, 'r') as csvfile:
    readCSV = csv.reader(csvfile)
    header = next(readCSV)
    if header != None:
        for row in readCSV:
            current_id = str(row[0])
            current_prediction = int(row[2])
            current_confidence = float(row[3])

            # make a copy of the file if the confidence is greater than a given threshold
            if (current_confidence >= confidence_threshold):
                if (current_prediction == 0):
                    shutil.copy(current_id, destination_directory)